name: Send Worship Schedule

on:
  schedule:
    # Запуск кожні 5 хвилин (для тестування)
    - cron: "0 6 * * 1"
  workflow_dispatch: # Залишаємо можливість ручного запуску

jobs:
  build-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4 # ТУТ БУЛА ПОМИЛКА
        with:
          node-version: "20"
          cache: "npm" # Додаємо кешування для швидкості

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Hard Debug
        run: |
          echo "--- START DEBUG ---"
          if [ -z "$SPREADSHEET_ID" ]; then echo "SPREADSHEET_ID is NULL in env"; else echo "SPREADSHEET_ID has value"; fi
          if [ -z "$BOT_TOKEN" ]; then echo "BOT_TOKEN is NULL in env"; else echo "BOT_TOKEN has value"; fi
          echo "--- END DEBUG ---"
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Run script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
          SHEET_RANGE: ${{ secrets.SHEET_RANGE }}
        run: node dist/index.js
